apiVersion: v1
kind: Pod
metadata:
  name: python-pod
spec:
  containers:
  - name: python-container
    image: python:3.8
    command: ["python", "sentinel-client.py"]
    - containerPort: 80
    imagePullPolicy: Always
