apiVersion: v1
kind: Pod
metadata:
  name: python-sentinel-client
  namespace: redis-ha
spec:
  containers:
  - name: sentinel-client
    image: artifactory.rafael.co.il:6001/python:3.11-slim
    # Override default command to run the mounted script
    command: ["/bin/sh", "-c"]
    args:
      - |
        pip install redis sentinel && 
        python /scripts/sentinel-client.py
    resources:
      requests:
        memory: "128Mi"  # Guaranteed minimum RAM
        cpu: "250m"      # Guaranteed minimum CPU (0.25 core)
      limits:
        memory: "256Mi"  # Hard ceiling for RAM
        cpu: "500m"      # Hard ceiling for CPU (0.5 core)
    env:
    - name: REDIS_HOST
      value: "redis-ha"
    volumeMounts:
    - name: script-volume
      mountPath: /scripts
  volumes:
  - name: script-volume
    configMap:
      name: sentinel-client-cm
      # Set permissions to allow execution (optional for python, mandatory for shell)
      defaultMode: 0744 
  restartPolicy: Never
  imagePullSecrets:
  - name: tsgs-registry