## Globally shared configuration
global:
  # -- Default priority class for all components
  priorityClassName: ""
  # -- Openshift compatibility options
  compatibility:
    openshift:
      adaptSecurityContext: auto

## -- Image information for Redis HA
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
image:
  # -- Redis image repository
  repository: artifactory.rafael.co.il:6001/redis
  # -- Redis image tag
  tag: 7.4.8
  # -- Redis image pull policy
  pullPolicy: IfNotPresent

imagePullSecrets: 
- name: "tsgs-registry"

# -- Number of redis master/slave
replicas: 3


## Redis specific configuration options
redis:
  config:
    save: "10 1"
    stop-writes-on-bgsave-error: "yes"
    rdbcompression: "yes"
    rdbchecksum: "yes"
    notify-keyspace-events: "EKxh"

  # -- CPU/Memory for master/slave nodes resource requests/limits
  resources: 
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 700Mi

auth: true
redisPassword: "tsgspasswd"

sentinel:
  # -- CPU/Memory for sentinel node resource requests/limits
  resources: 
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 200Mi 
  
  auth: true
  password: "tsgspasswd"

persistentVolume:
  # -- Enable persistent volume
  enabled: true
  storageClass: trident-csi
  # -- Persistent volume access modes
  accessModes:
    - ReadWriteOnce
  # -- Persistent volume size
  size: 10Gi
  # -- Annotations for the volume
  annotations: {}
  # -- Labels for the volume
  labels: {}

exporter:
  # -- If `true`, the prometheus exporter sidecar is enabled
  enabled: true
  # -- Exporter image
  image: artifactory.rafael.co.il:6001/oliver006/redis_exporter
  # -- Exporter image tag
  tag: v1.80.2
  # -- Exporter image pullPolicy
  pullPolicy: IfNotPresent

  # -- Exporter port
  port: &exporter_port 9121
  # -- Exporter port name
  portName: exporter-port
  # -- Exporter scrape path
  scrapePath: &exporter_scrapePath /metrics
