apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config-cm
  namespace: default
data:
  redis.conf: |
    save 10 1
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum no
    notify-keyspace-events EKxh
