kind: Redis
apiVersion: redis.redis.opstreelabs.in/v1beta1
metadata:
  name: redis-standalone
  namespace: default
spec:
  kubernetesConfig:
    image: 'artifactory.rafael.co.il:6001/opstree/redis:v6.2.20'
    imagePullPolicy: IfNotPresent
    imagePullSecrets:
      - name: tsgs-registry
    resources:
      requests:
        cpu: 1000m
        memory: 2Gi
      limits:
        cpu: 2000m
        memory: 4Gi
    redisSecret:
      name: redis-secret
      key: password
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  redisExporter:
    enabled: true
    image: 'artifactory.rafael.co.il:6001/opstree/redis-exporter:v1.44.0'
    imagePullPolicy: IfNotPresent
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
  redisConfig:
    save 10 1
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes
    notify-keyspace-events EKxh

